In [1]:
import tensorflow as tf
print("TensorFlow version:{}".format(tf.__version__))

TensorFlow version:2.18.0


In [2]:
d0=tf.constant(1)
print("Dimension is",tf.rank(d0).numpy())
print(d0)

Dimension is 0
tf.Tensor(1, shape=(), dtype=int32)


n=1 : Vector

In [3]:
d1=tf.ones((2,))
print("Dimension is",tf.rank(d1).numpy())
print(d1)

Dimension is 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


n=2 : Martix

In [4]:
d2=tf.ones((2,2))
print("Dimension is",tf.rank(d2).numpy())
print(d2)

Dimension is 2
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


n=3 : N-Dimension Metrix

In [5]:
d3=tf.ones((2,2,2))
print("Dimension is",tf.rank(d3).numpy())
print(d3)

Dimension is 3
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [6]:
#rank 0 tensor
x1= tf.Variable(23)
#rank 3 tensor
x2=tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]])
#python variable
x0=123
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

constant

In [7]:
x1.assign(100)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>

In [8]:
x1=tf.Variable(100)   #x1=tf.constant(100)
print(x1)
x1.assign(200)
x1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=200>

In [9]:
x2

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [10]:
x0

123

**Reshape**

In [11]:
x112=tf.reshape(x2,[1,12]) #12 rows one column
x112

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

Declaring Variable with Type

In [12]:
xf64=tf.Variable(202,dtype=tf.float64)
xf64.dtype

tf.float64

In [13]:
xf64.numpy()

np.float64(202.0)

Ranking check dimensions variable

In [14]:
tf.rank(xf64)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [15]:
tf.rank(x2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
t=tf.constant([[[1,1,1],[2,2,2]],[[4,3,5],[4,4,414]]])
tf.rank(t).numpy()

np.int32(3)

In [17]:
t.numpy()

array([[[  1,   1,   1],
        [  2,   2,   2]],

       [[  4,   3,   5],
        [  4,   4, 414]]], dtype=int32)

Tensor Slicing

In [18]:
tensor3=t[1,1,2]  #slice1,row0,column2
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=414>

In [19]:
x=tf.constant([0,1,1,2,3,4,8,13,21,34])
print("Before 4:",x[:4].numpy())
print("After 4:",x[4:].numpy())
print("From 2,before 7:",x[2:7].numpy())
print("Every other item:",x[::2].numpy())
print("Reversed:",x[::-1].numpy())

Before 4: [0 1 1 2]
After 4: [ 3  4  8 13 21 34]
From 2,before 7: [1 2 3 4 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  4  3  2  1  1  0]


Casting Tensor to a datatype

In [20]:
a=tf.constant([[1,2],[3,4]])
i=tf.cast(a,dtype=tf.float32)
print(a)
print(i)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


Tensor Operation

In [21]:
a= tf.constant([[1,2],[3,4]])
b= tf.constant([[5,6],[7,8]])
c = a +b

In [22]:
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [23]:
b.numpy()

array([[5, 6],
       [7, 8]], dtype=int32)

In [24]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [25]:
print(b)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [26]:
print("\n output of c",c)


 output of c tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [27]:
d =tf.square(c)
print(d)

tf.Tensor(
[[ 36  64]
 [100 144]], shape=(2, 2), dtype=int32)


In [28]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

In [29]:
tf.subtract(b,a)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]], dtype=int32)>

In [30]:
e= a*b
print(e)
tf.multiply(a,b) # No of columns in a == No of Rows in b tensor

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>